version: "3.8"

services:
  app:
    container_name: nextjs-demo
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules # Avoid installing node_modules inside the container if using volumes
      - ./public:/app/public # Include other project directories if needed
      - ./package.json:/app/package.json # In case you need to synchronize package.json
      - ./yarn.lock:/app/yarn.lock # To ensure consistent dependencies
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: yarn next dev
